{{- if and .Values.readarr.enabled .Values.readarr.persistence.enabled (not .Values.readarr.persistence.existingClaim) }}
{{- include "pindaroli-common.pvc" (dict "root" . "component" "readarr") -}}
{{- end }}
