name: excalidraw
maintainers:
  - name: pindarolidev
    url: https://pindaroli.org
apiVersion: v2
appVersion: 0.17.6
version: 1.0.0
description: Pindaroli Excalidraw Helm Chart
home: https://github.com/pindarolidev/helm/tree/main/charts/excalidraw
icon: https://pindaroli.org/images/pindaroli.svg
keywords:
  - kubernetes
  - excalidraw
  - diagrams
  - design
sources:
  - https://github.com/excalidraw/excalidraw
