{{- if and .Values.sonarr.enabled .Values.sonarr.persistence.enabled (not .Values.sonarr.persistence.existingClaim) }}
{{- include "pindaroli-common.pvc" (dict "root" . "component" "sonarr") -}}
{{- end }}
