{{- if and .Values.radarr.enabled .Values.radarr.persistence.enabled (not .Values.radarr.persistence.existingClaim) }}
{{- include "pindaroli-common.pvc" (dict "root" . "component" "radarr") -}}
{{- end }}
