{{- if (index .Values "jellyfin-classic").enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jellyfin-classic
  labels:
    app.kubernetes.io/name: jellyfin-classic
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  strategy:
    type: Recreate
  replicas: {{ (index .Values "jellyfin-classic").replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin-classic
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin-classic
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    spec:
    {{- if (index .Values "jellyfin-classic").enableDLNA }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    {{- end }}
    {{- if and (index .Values "jellyfin-classic").tailscale.enabled (index .Values "jellyfin-classic").tailscale.sidecar.enabled }}
      serviceAccountName: jellyfin-classic-tailscale
    {{- end }}
      containers:
    {{- if and (index .Values "jellyfin-classic").tailscale.enabled (index .Values "jellyfin-classic").tailscale.sidecar.enabled }}
        - name: tailscale-sidecar
          image: ghcr.io/tailscale/tailscale:latest
          env:
            - name: TS_KUBE_SECRET
              value: {{ (index .Values "jellyfin-classic").tailscale.sidecar.existingAuthSecret | default "jellyfin-classic-tailscale-auth-secret" }}
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: {{ (index .Values "jellyfin-classic").tailscale.sidecar.existingAuthSecret | default "jellyfin-classic-tailscale-auth-secret" }}
                  key: TS_AUTHKEY
            - name: TS_USERSPACE
              value: "false"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
    {{- end }}
        - name: {{ .Release.Name }}-jellyfin-classic
          image: "{{ (index .Values "jellyfin-classic").image.repository }}:{{ (index .Values "jellyfin-classic").image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ (index .Values "jellyfin-classic").image.pullPolicy }}
        {{ if (index .Values "jellyfin-classic").extraEnvVars }}
          env:
            {{- toYaml (index .Values "jellyfin-classic").extraEnvVars | nindent 12 }}
        {{- end }}
        {{ if (index .Values "jellyfin-classic").securityContext }}
          securityContext:
            {{- toYaml (index .Values "jellyfin-classic").securityContext | nindent 12 }}
        {{- end }}
          ports:
            - name: http
              containerPort: {{ (index .Values "jellyfin-classic").service.port }}
              protocol: TCP
          {{ if (index .Values "jellyfin-classic").enableDLNA }}
            - name: dlna
              containerPort: 1900
              hostPort: 1900
              protocol: UDP
          {{- end }}
        {{ if (index .Values "jellyfin-classic").livenessProbe.enabled }}
          livenessProbe:
          {{ if (index .Values "jellyfin-classic").livenessProbe.initialDelaySeconds }}
            initialDelaySeconds: {{ (index .Values "jellyfin-classic").livenessProbe.initialDelaySeconds }}
          {{- end }}
          {{ if (index .Values "jellyfin-classic").livenessProbe.periodSeconds }}
            periodSeconds: {{ (index .Values "jellyfin-classic").livenessProbe.periodSeconds }}
          {{- end }}
          {{ if (index .Values "jellyfin-classic").livenessProbe.timeoutSeconds }}
            timeoutSeconds: {{ (index .Values "jellyfin-classic").livenessProbe.timeoutSeconds }}
          {{- end }}
          {{ if (index .Values "jellyfin-classic").livenessProbe.failureThreshold }}
            failureThreshold: {{ (index .Values "jellyfin-classic").livenessProbe.failureThreshold }}
          {{- end }}
          {{ if (index .Values "jellyfin-classic").livenessProbe.successThreshold }}
            successThreshold: {{ (index .Values "jellyfin-classic").livenessProbe.successThreshold }}
          {{- end }}
            tcpSocket:
              port: http
        {{- end }}
        {{ if (index .Values "jellyfin-classic").readinessProbe.enabled }}
          readinessProbe:
          {{ if (index .Values "jellyfin-classic").readinessProbe.initialDelaySeconds }}
            initialDelaySeconds: {{ (index .Values "jellyfin-classic").readinessProbe.initialDelaySeconds }}
          {{- end }}
          {{ if (index .Values "jellyfin-classic").readinessProbe.periodSeconds }}
            periodSeconds: {{ (index .Values "jellyfin-classic").readinessProbe.periodSeconds }}
          {{- end }}
          {{ if (index .Values "jellyfin-classic").readinessProbe.timeoutSeconds }}
            timeoutSeconds: {{ (index .Values "jellyfin-classic").readinessProbe.timeoutSeconds }}
          {{- end }}
          {{ if (index .Values "jellyfin-classic").readinessProbe.failureThreshold }}
            failureThreshold: {{ (index .Values "jellyfin-classic").readinessProbe.failureThreshold }}
          {{- end }}
          {{ if (index .Values "jellyfin-classic").readinessProbe.successThreshold }}
            successThreshold: {{ (index .Values "jellyfin-classic").readinessProbe.successThreshold }}
          {{- end }}
            tcpSocket:
              port: http
        {{- end }}
          volumeMounts:
            - mountPath: /config
              name: config
            {{- if (index .Values "jellyfin-classic").persistence.config.subPath }}
              subPath: {{ (index .Values "jellyfin-classic").persistence.config.subPath }}
            {{- end }}
            {{- range (index .Values "jellyfin-classic").persistence.extraExistingClaimMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
            {{- if (index .Values "jellyfin-classic").extraVolumeMounts }}
            {{- toYaml (index .Values "jellyfin-classic").extraVolumeMounts | nindent 12 }}
            {{- end }}
            {{- if (index .Values "jellyfin-classic").persistence.media.enabled }}
            - mountPath: /media/music/classical
              name: media
              {{- if (index .Values "jellyfin-classic").persistence.media.subPath }}
              subPath: {{ (index .Values "jellyfin-classic").persistence.media.subPath }}
              {{- end }}
              readOnly: true
            {{- end }}
          {{- if (index .Values "jellyfin-classic").extraContainers }}
          {{- toYaml (index .Values "jellyfin-classic").extraContainers | nindent 8 }}
          {{- end }}
          resources:
{{ toYaml (index .Values "jellyfin-classic").resources | indent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
          securityContext: {{- toYaml (index .Values "jellyfin-classic").securityContext | nindent 12 }}
  {{- if (index .Values "jellyfin-classic").extraInitContainers }}
      initContainers:
      {{- toYaml (index .Values "jellyfin-classic").extraInitContainers | nindent 10 }}
  {{- end }}
      volumes:
      - name: config
      {{- if (index .Values "jellyfin-classic").persistence.config.enabled }}
        persistentVolumeClaim:
          claimName: {{ if (index .Values "jellyfin-classic").persistence.config.existingClaim }}{{ (index .Values "jellyfin-classic").persistence.config.existingClaim }}{{- else }}{{ .Release.Name }}-jellyfin-classic-config{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: media
      {{- if (index .Values "jellyfin-classic").persistence.media.enabled }}
        persistentVolumeClaim:
          claimName: {{ if (index .Values "jellyfin-classic").persistence.media.existingClaim }}{{ (index .Values "jellyfin-classic").persistence.media.existingClaim }}{{- else }}{{ .Release.Name }}-jellyfin-classic-media{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- range (index .Values "jellyfin-classic").persistence.extraExistingClaimMounts }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .existingClaim }}
      {{- end }}
      {{- if (index .Values "jellyfin-classic").extraVolumes }}
      {{- toYaml (index .Values "jellyfin-classic").extraVolumes | nindent 6 }}
      {{- end }}
    {{- with (index .Values "jellyfin-classic").nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with (index .Values "jellyfin-classic").affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with (index .Values "jellyfin-classic").tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      securityContext: {{- toYaml (index .Values "jellyfin-classic").podSecurityContext | nindent 8 }}
{{- end }}
