{{- if and (index .Values "jellyfin-classic").enabled (index .Values "jellyfin-classic").persistence.config.enabled (not (index .Values "jellyfin-classic").persistence.config.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-jellyfin-classic-config
  labels:
    app.kubernetes.io/name: jellyfin-classic
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with (index .Values "jellyfin-classic").persistence.config.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (index .Values "jellyfin-classic").persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ (index .Values "jellyfin-classic").persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ (index .Values "jellyfin-classic").persistence.config.size | quote }}
  {{- if (index .Values "jellyfin-classic").persistence.config.storageClass }}
  {{- if (eq "-" (index .Values "jellyfin-classic").persistence.config.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ (index .Values "jellyfin-classic").persistence.config.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}

---
{{- if and (index .Values "jellyfin-classic").persistence.media.enabled (not (index .Values "jellyfin-classic").persistence.media.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-jellyfin-classic-media
  labels:
    app.kubernetes.io/name: jellyfin-classic
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with (index .Values "jellyfin-classic").persistence.media.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with (index .Values "jellyfin-classic").persistence.media.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ (index .Values "jellyfin-classic").persistence.media.accessMode | quote }}
  resources:
    requests:
      storage: {{ (index .Values "jellyfin-classic").persistence.media.size | quote }}
  {{- if (index .Values "jellyfin-classic").persistence.media.storageClass }}
  {{- if (eq "-" (index .Values "jellyfin-classic").persistence.media.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ (index .Values "jellyfin-classic").persistence.media.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
