{{- if and (index .Values "jellyfin-classic").enabled (index .Values "jellyfin-classic").tailscale.enabled (index .Values "jellyfin-classic").tailscale.sidecar.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: jellyfin-classic-tailscale-auth-secret
  labels:
    app.kubernetes.io/name: jellyfin-classic
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
  TS_AUTHKEY: {{ (index .Values "jellyfin-classic").tailscale.sidecar.authKey | b64enc }}
{{- end }}
