{{- if (index .Values "jellyfin-classic").enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jellyfin-classic
  labels:
    app.kubernetes.io/name: jellyfin-classic
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- if (index .Values "jellyfin-classic").service.labels }}
  {{ toYaml (index .Values "jellyfin-classic").service.labels | indent 4 }}
  {{- end }}
  {{- with (index .Values "jellyfin-classic").service.annotations }}
  annotations:
    {{- toYaml . | indent 4 }}
  {{- end }}
spec:
  {{- if (or (eq (index .Values "jellyfin-classic").service.type "ClusterIP") (empty (index .Values "jellyfin-classic").service.type)) }}
  type: ClusterIP
  {{- if (index .Values "jellyfin-classic").service.clusterIP }}
  clusterIP: {{ (index .Values "jellyfin-classic").service.clusterIP }}
  {{end}}
  {{- else if eq (index .Values "jellyfin-classic").service.type "LoadBalancer" }}
  type: {{ (index .Values "jellyfin-classic").service.type }}
  {{- if (index .Values "jellyfin-classic").service.loadBalancerIP }}
  loadBalancerIP: {{ (index .Values "jellyfin-classic").service.loadBalancerIP }}
  {{- end }}
  {{- if (index .Values "jellyfin-classic").service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml (index .Values "jellyfin-classic").service.loadBalancerSourceRanges | indent 4 }}
  {{- end -}}
  {{- else }}
  type: {{ (index .Values "jellyfin-classic").service.type }}
  {{- end }}
  {{- if (index .Values "jellyfin-classic").service.externalIPs }}
  externalIPs:
    {{- toYaml (index .Values "jellyfin-classic").service.externalIPs | indent 4 }}
  {{- end }}
  {{- if (index .Values "jellyfin-classic").service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ (index .Values "jellyfin-classic").service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - name: http
      port: {{ (index .Values "jellyfin-classic").service.port }}
      protocol: TCP
      targetPort: http
  {{ if (and (eq (index .Values "jellyfin-classic").service.type "NodePort") (not (empty (index .Values "jellyfin-classic").service.nodePort))) }}
      nodePort: {{ (index .Values "jellyfin-classic").service.nodePort }}
  {{ end }}
  selector:
    app.kubernetes.io/name: jellyfin-classic
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
