{{- if and (index .Values "jellyfin-classic").enabled (index .Values "jellyfin-classic").tailscale.enabled (index .Values "jellyfin-classic").tailscale.sidecar.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin-classic-tailscale

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jellyfin-classic-tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ (index .Values "jellyfin-classic").tailscale.sidecar.existingAuthSecret | default "jellyfin-classic-tailscale-auth-secret" }}"]
    verbs: ["get", "update", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jellyfin-classic-tailscale
subjects:
  - kind: ServiceAccount
    name: jellyfin-classic-tailscale
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: jellyfin-classic-tailscale
  apiGroup: rbac.authorization.k8s.io
{{ end }}
