{{- if .Values.minimserver.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" .Release.Name "minimserver" }}
  labels:
    app.kubernetes.io/name: minimserver
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- end }}
