name: servarr
maintainers:
  - name: pindaroli
    url: https://github.com/pindaroli
apiVersion: v2
appVersion: 1.1.7
version: 1.5.1
description: Pindaroli Servarr Helm Chart
home: https://github.com/pindaroli/pindaroli-arr-helm/tree/main/charts/servarr
icon: https://pindaroli.github.io/pindaroli-arr-helm//images/pindaroli.svg
keywords:
  - kubernetes
  - bazarr
  - lidarr
  - sonarr
  - radarr
  - readarr
  - flaresolverr
  - jellyfin
  - jellyseerr
  - qbittorrent
  - prowlarr
  - cleanuperr
  - recyclarr
  - autobrr
sources:
  - https://github.com/Servarr

dependencies:
  - name: pindaroli-common
    version: 1.0.1
    repository: "file://../pindaroli-common"

# Trigger release pipeline fix
