name: servarr
maintainers:
  - name: pindaroli
    url: https://github.com/pindaroli
apiVersion: v2
appVersion: 1.1.7
version: 1.1.9
description: Kubito Servarr Helm Chart
home: https://github.com/pindaroli/pindaroli-arr-helm/tree/main/charts/servarr
icon: https://kubito.dev/images/kubito.svg
keywords:
  - kubernetes
  - bazarr
  - lidarr
  - sonarr
  - radarr
  - readarr
  - flaresolverr
  - jellyfin
  - jellyseerr
  - qbittorrent
  - prowlarr
  - cleanuperr
sources:
  - https://github.com/Servarr
