{{- if and .Values.jellyseerr.enabled .Values.jellyseerr.persistence.enabled (not .Values.jellyseerr.persistence.existingClaim) }}
{{- include "pindaroli-common.pvc" (dict "root" . "component" "jellyseerr") -}}
{{- end }}
