name: penpot
maintainers:
  - name: pindarolidev
    url: https://pindaroli.org
apiVersion: v2
appVersion: 2.2.1
version: 1.2.1
description: Pindaroli Penpot Helm Chart
home: https://github.com/pindarolidev/helm/tree/main/charts/penpot
icon: https://pindaroli.github.io/pindaroli-arr-helm//images/pindaroli.svg
keywords:
  - kubernetes
  - penpot
  - penpotapp
  - design
sources:
  - https://github.com/penpot/penpot

dependencies:
  - condition: global.postgresqlEnabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.x.x
  - condition: global.redisEnabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.x.x
