name: traefik-cloudflared-source-ip
maintainers:
  - name: pindarolidev
    url: https://pindaroli.org
apiVersion: v2
appVersion: 2.10.7
version: 1.2.6
description: Pindaroli Traefik Cloudflared (Argo Tunnel) Real IP Helm Chart
home: https://github.com/pindarolidev/helm/tree/main/charts/traefik-cloudflared-source-ip
icon: https://pindaroli.github.io/pindaroli-arr-helm/images/pindaroli.svg
keywords:
  - kubernetes
  - cloudflare
  - cloudflared
  - middleware
  - real-ip
  - source-ip
  - argo-tunnel
  - argo
  - traefik
sources:
  - https://github.com/pindarolidev/traefik-cloudflared-source-ip

dependencies:
  - condition: global.cloudflaredEnabled
    name: cloudflared
    repository: "https://pindaroli.github.io/pindaroli-arr-helm/"
    # https://github.com/Masterminds/semver#checking-version-constraints
    version: 1.2.6
  - condition: global.traefikEnabled
    name: traefik
    repository: "https://pindaroli.github.io/pindaroli-arr-helm/"
    version: 1.2.6
