name: traefik-whitelist-ddns
maintainers:
  - name: pindarolidev
    url: https://pindaroli.org
apiVersion: v2
appVersion: 2.x.x
version: 1.0.5
description: Pindaroli Traefik Whitelist DDNS Helm Chart
home: https://github.com/pindarolidev/helm/tree/main/charts/traefik-whitelist-ddns
icon: https://pindaroli.org/images/pindaroli.svg
keywords:
  - kubernetes
  - traefik
  - ddns
  - cronjob
  - middleware
  - ip
  - whitelist
sources:
  - https://github.com/pindarolidev/traefik-whitelist-ddns
