{{- if and .Values.prowlarr.enabled .Values.prowlarr.persistence.enabled (not .Values.prowlarr.persistence.existingClaim) }}
{{- include "pindaroli-common.pvc" (dict "root" . "component" "prowlarr") -}}
{{- end }}
