{{- if .Values.qbittorrent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-qbittorrent-trigger-job
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
data:
  trigger-job.sh: |
{{ tpl (.Files.Get "files/trigger-job.sh") . | indent 4 }}
{{- end }}
