{{- if and .Values.bazarr.enabled .Values.bazarr.persistence.enabled (not .Values.bazarr.persistence.existingClaim) }}
{{- include "pindaroli-common.pvc" (dict "root" . "component" "bazarr") -}}
{{- end }}
