{{- if and .Values.lidarr.enabled .Values.lidarr.persistence.enabled (not .Values.lidarr.persistence.existingClaim) }}
{{- include "pindaroli-common.pvc" (dict "root" . "component" "lidarr") -}}
{{- end }}
