name: cloudflared
maintainers:
  - name: pindarolidev
    url: https://pindaroli.org
apiVersion: v2
appVersion: 2025.5.0
version: 1.7.1
description: Pindaroli Cloudflared (Argo Tunnel) Helm Chart
home: https://github.com/pindarolidev/helm/tree/main/charts/cloudflared
icon: https://pindaroli.github.io/pindaroli-arr-helm/images/pindaroli.svg
keywords:
  - kubernetes
  - cloudflare
  - cloudflared
  - argo
  - tunnel
sources:
  - https://github.com/cloudflare/cloudflared
