name: kubernetes-cloudflare-ddns
maintainers:
  - name: pindarolidev
    url: https://pindaroli.org
apiVersion: v2
appVersion: 1.0.1
version: 1.0.6
description: Pindaroli Kubernetes Cloudflare DDNS Helm Chart
home: https://github.com/pindarolidev/helm/tree/main/charts/kubernetes-cloudflare-ddns
icon: https://pindaroli.github.io/pindaroli-arr-helm/images/pindaroli.svg
keywords:
  - kubernetes
  - cloudflare
  - ddns
  - cronjob
sources:
  - https://github.com/pindarolidev/kubernetes-cloudflare-ddns
