{{- if and (index .Values "lidarr-classic").enabled (index .Values "lidarr-classic").autoscaling.enabled }}
{{- include "pindaroli-common.hpa" (dict "root" . "component" "lidarr-classic") -}}
{{- end }}
