{{- if and (index .Values "lidarr-classic").enabled (index .Values "lidarr-classic").serviceAccount.create }}
{{- include "pindaroli-common.serviceaccount" (dict "root" . "component" "lidarr-classic") -}}
{{- end }}
